!Blockwork
project: example
bootstrap:
  - infra.bootstrap.tools
  - infra.bootstrap.pythonsite
tooldefs:
  - infra.tools.misc
  - infra.tools.compilers
  - infra.tools.simulators
  - infra.tools.wave_viewers
transforms:
  - infra.transforms.lint
  - infra.transforms.templating
entities:
  - design.top
