!Blockwork
project: example
site: ./site.yaml
tooldefs:
  - infra.tools.misc
  - infra.tools.compilers
  - infra.tools.simulators
  - infra.tools.wave_viewers
transforms:
  - infra.transforms.lint
  - infra.transforms.templating
  - infra.transforms.examples
workflows:
  - infra.workflows
config:
  - infra.config.config

