!Blockwork
project: example
site: ./site.yaml
tooldefs:
  - infra.tools.misc
  - infra.tools.compilers
  - infra.tools.simulators
  - infra.tools.wave_viewers
transforms:
  - infra.transforms.lint
  - infra.transforms.templating
workflows:
  - infra.workflows.lint
config:
  - infra.config.config
entities:
  - design.top.top
