!Blockwork
project: example
site: ./site.yml
bootstrap:
  - infra.bootstrap.tools
  - infra.bootstrap.pythonsite
tooldefs:
  - infra.tools.misc
  - infra.tools.compilers
  - infra.tools.simulators
  - infra.tools.wave_viewers
transforms:
  - infra.transforms.lint
  - infra.transforms.templating
config:
  - infra.config.config
entities:
  - design.top
