!Blockwork
project: example
site: ./site.yaml
default_cache_config: ./caches.yaml
tooldefs:
  - infra.tools.misc
  - infra.tools.compilers
  - infra.tools.simulators
  - infra.tools.wave_viewers
workflows:
  - infra.workflows
caches:
  - infra.caches.BasicFileCache
config:
  - infra.config.config
