site_name: Blockwork
repo_name: intuity/blockwork
repo_url: https://github.com/intuity/Blockwork
theme:
  name: material
  logo: assets/mascot_white.svg
  palette:
    scheme: slate
    primary: indigo
  features:
    - search.suggest
    - search.highlight
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Welcome: "index.md"
  - Foundations: "foundations.md"
  - Technologies:
    - Containers: "tech/containers.md"
    - State: "tech/state.md"
  - Configuration:
    - ".bw.yaml": "config/bw_yaml.md"
  - Syntax:
    - Bootstrap: "syntax/bootstrap.md"
    - Tools: "syntax/tools.md"
    - Tools: "syntax/transforms.md"
  - "Command Line Interface":
    - Introduction: "cli/introduction.md"
    - bootstrap: "cli/bootstrap.md"
    - info: "cli/info.md"
    - exec: "cli/exec.md"
    - shell: "cli/shell.md"
    - tool: "cli/tool.md"
    - tools: "cli/tools.md"
